name: CI Workflow
"on": 
  push:
    branches:
      - main2
  pull_request:
    branches:
      - main2
  workflow_dispatch:

defaults:
  run:
    shell: bash
jobs:
  validate-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          presistent-credentials: false
      - name: validate the yaml file
        run: >
          yamllint --config-data "{extends: relaxed, rules: {line-length: disable}, ignore: [charts/, templates/, .garden/, vendor/]}" .
      - name: Debug mode
        if: failure() || runner.debug && always()
        uses: uniphore/platform-github-actions/.github/actions/debug@main
    timeout-minutes: 30