name : Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
    branches:
      - sanjay/new
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world 2"
        shell: bash
  goodbye:
    runs-on : ubuntu-latest
    steps:
      - name: goodbye world
        if: github.event_name == 'pull_request'
        run: echo "${{ github.event.pull_request.head.sha }}"
      - name: hello world
        run: echo "Hello world 2"
        

