name : Hello world workflow
on:
  push:
    branches:
      - sanjay/new
  pull_request:
    types: [opened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world 2"
        shell: bash
  goodbye:
    runs-on : ubuntu-latest
    steps:
      - name: goodbye world
        id: empt
        run: echo "v=${{ github.event.head_commit.id }}" >> "${GITHUB_OUTPUT}"
      - name: hello world
        if: contains(github.event.head_commit.id,"")
        run: |
          echo "No id"
        

