name : Hello world workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello world 2"
        shell: bash
  goodbye:
    runs-on : ubuntu-latest
    steps:
      - name: goodbye world
        run: echo "${{ github.event.head_commit.id }}"
      - name: hello world
        run: echo "Hello world 324"
        

