name: Create a aomment on new issues

on:
  issue:
    types: [opened]

jobs:
  comment-with-actions: 
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run : echo '${{toJSON(github.event) }}'
        shell: bash
